language:
- java
script:
- ./gradlew test uploadArchive
jdk:
- oraclejdk7
env:
  global:
  - secure: bfJjBKzoyua5SXEPOb2bY+BtDtsUhkawzENmfxkLPgKwV1/M8TgJgOU5yyh6rHnMHRioOn4mWc0ral1dNZAhNRkny+w2dNlSEbBqF1Tm50Z51ompfdCJKw1BWDMof3Z7sfbXO7qSU8BnRpwPsCHvsC+PdCaGRPiNWHRJibWiafw=
  - secure: P7BSixL8iu3LsqppM6hUfzpALpCJAyc6yBPuIVBOQFwPEmfoSnKIECS3XDo9KEg57iomjxTdl3/q3TT08y+bV9q90Gs5argxk8E9dNfrU0W8WJV6OFGPYjiZ+yDvMbD98yjhIR5iGw/H7DhU1XbkfIUhoXTPjGk8wkkOCPh2fek=
