language: java
script:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./gradlew uploadArchives; else ./gradlew test; fi
jdk:
- oraclejdk7
env:
  global:
  - secure: FIV83gG41ENnn0DFYaM/c/2wa/gFCLYSY3o+UnuCPsGqHuApdQkFOHjsrPLJMjfGLJqTJuWt2sG2DwAiWZwHU1DvbgTQNVMhwc3gBlQj2fPI/bmJwEBKPrMTcxbih4hl6fRoVEzp2ZHINbY40WfZK+087edGLapas2KA41YwW1o=
  - secure: WQ9cyFXtLFuFASW5K/TuwXeHeDZPYdOYdZniHJqEBzhMKodfH5a/knOjlU0NuKjL2aqcmznnNQGAsiCBTfKrdnXQhOxz8ce8BxGEVHQMODpFbZ5xpEA0oboL06ixEUGieZ1OC67JxPMTmbinGnwMKyPs04WXKKHhtOIvy7GSDrY=
